name: n8n Workflow Automation

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.2.1@sha256:ee59276d9d5c7daa97462830cfae12d71cea55adcad705e1756e0c616fcf26b9
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n_storage:/home/node/.n8n
      - /opt/docker/n8n/n8n.key:/var/run/secrets/n8n.key
    secrets:
     - source: server-cert
       target: n8n.crt
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=true
      - N8N_SSL_CERT=/var/run/secrets/n8n.crt
      - N8N_SSL_KEY=/var/run/secrets/n8n.key
    ports:
      - '5678:5678'
    networks:
      - proxy_net
      - n8n_internal
    restart: always
    links:
      - postgres
        
  postgres:
    image: postgres:16@sha256:d4c3314b2dd74ff23cd6cd07e4d7e737cb6ef791c22a7cbd744cfbfb4815df72
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    networks:
      - n8n_internal
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  n8n_internal:
    internal: true
    name: n8n_internal_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.12.64/28
          gateway: 172.27.12.65
  proxy_net:
    external: true
    name: network_backend_net

volumes:
  db_storage:
  n8n_storage:

secrets:
  server-cert:
    file: "/opt/docker/rootca/public/n8n.crt"
